#pragma once

#define MASTER_LEFT

#define TAPPING_TERM 180

#define ONESHOT_TIMEOUT 500

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 251

#define ENABLE_COMPILE_KEYCODE

#define MK_KINETIC_SPEED
#define MOUSEKEY_MOVE_DELTA 29

#define DEBOUNCE 10
